module.exports = {
    "language": "EN",
    "video_shorts_data": {
        "hookTitle": "AMD DEPLOYS 2GW INSTINCT MI450 GPUS FOR ANTHROPIC",
        "totalDurationSeconds": 30,
        "script_slides": [
            {
                "slide_index": 1,
                "headline": "AMD: 2GW INSTINCT MI450 DEPLOYMENT",
                "teaserTitle": "NVIDIA: NEMOTRON 3.5 LIGHTNING RELEASE",
                "visual_asset": "backgroundyt1.png",
                "narration_line": "AMD and Anthropic have announced a strategic partnership to deploy up to two gigawatts of Instinct MI450 Series GPUs. This landmark deal secures unprecedented compute capacity for next generation frontier Claude models."
            },
            {
                "slide_index": 2,
                "headline": "NVIDIA: NEMOTRON 3.5 LIGHTNING RELEASE",
                "teaserTitle": "MICROSOFT: AZURE LAUNCHES AMD VIRTUAL MACHINES",
                "visual_asset": "backgroundyt2.png",
                "narration_line": "NVIDIA has launched Nemotron 3.5 Lightning alongside NeMo Switchyard to accelerate agentic AI deployments. The architecture enables ultra fast model routing to optimize speed, accuracy, and operational compute cost."
            },
            {
                "slide_index": 3,
                "headline": "MICROSOFT: AZURE LAUNCHES AMD VIRTUAL MACHINES",
                "teaserTitle": "OPENAI: DAYBREAK AI CYBER DEFENSE EXPANSION",
                "visual_asset": "backgroundyt3.png",
                "narration_line": "Microsoft Azure expanded its AI infrastructure with new virtual machines powered by AMD Instinct MI455X accelerators. These instances deliver high performance scaling for complex enterprise training and real-time inference workloads."
            },
            {
                "slide_index": 4,
                "headline": "OPENAI: DAYBREAK AI CYBER DEFENSE EXPANSION",
                "teaserTitle": "AMD: OXFORD FRONTIER AI LAB PARTNERSHIP",
                "visual_asset": "backgroundyt4.png",
                "narration_line": "OpenAI expanded its Daybreak cybersecurity platform as the window against autonomous digital threats narrows. The updated toolkit equips enterprise security teams with real time defense systems to neutralize threat agents."
            },
            {
                "slide_index": 5,
                "headline": "AMD: OXFORD FRONTIER AI LAB PARTNERSHIP",
                "teaserTitle": "CODERABBIT: AGENTIC CODE CHANGE CONTROL",
                "visual_asset": "backgroundyt5.png",
                "narration_line": "AMD partnered with the University of Oxford to establish a dedicated frontier AI research initiative in the United Kingdom. The lab will focus on open-ended learning algorithms and advanced foundational model scaling."
            },
            {
                "slide_index": 6,
                "headline": "CODERABBIT: AGENTIC CODE CHANGE CONTROL",
                "teaserTitle": "IEEE SPECTRUM: AI DESIGNS FUNCTIONAL VIRUSES",
                "visual_asset": "backgroundyt6.png",
                "narration_line": "CodeRabbit introduced an Agentic Change Management platform to tackle code overload generated by automated AI assistants. The system validates and filters synthetic code reviews to maintain repository stability and quality."
            },
            {
                "slide_index": 7,
                "headline": "IEEE SPECTRUM: AI DESIGNS FUNCTIONAL VIRUSES",
                "teaserTitle": "FINAL SLIDE",
                "visual_asset": "backgroundyt7.png",
                "narration_line": "Researchers have successfully utilized generative artificial intelligence models to design functional biological viruses. The breakthrough underscores an urgent operational requirement for advanced biosecurity guardrails across public and private AI platforms."
            },
            {
                "slide_index": 8,
                "headline": "LIVE INTELLIGENCE",
                "teaserTitle": "",
                "visual_asset": "backgroundyt8.png",
                "narration_line": "Get the latest real-time tracking updates, market shifts, and hourly insights at aeon intel, Like Share and Follow for more."
            }
        ]
    }
};